CREATE DATABASE CAFETERIA

    CREATE TABLE CLIENTES (
        CLIENTE_ID SERIAL NOT NULL,
        CLIENTE_NOMBRE VARCHAR (25),
        CLIENTE_APELLIDO VARCHAR (25),
        CLIENTE_GENERO VARCHAR(50),
        CLIENTE_CORREO VARCHAR(50),
        CLIENTE_TELEFONO INTEGER,
        CLIENTE_SITUACION INTEGER DEFAULT 1,
        PRIMARY KEY (CLIENTE_ID)
    );

    CREATE TABLE EMPLEADOS(
        EMPLEADO_ID SERIAL NOT NULL,
        EMPLEADO_NOMBRE VARCHAR (25),
        EMPLEADO_APELLIDO VARCHAR (25),
        EMPLEADO_GENERO VARCHAR (15),
        EMPLEADO_PUESTO VARCHAR (20),
        EMPLEADO_NACIMIENTO DATE YEAR TO MINUTE,
        EMPLEADO_TELEFONO INTEGER,
        EMPLEADO_CORREO VARCHAR (50),
        EMPLEADO_ESTADO VARCHAR (15),
        EMPLEADO_CONTRA DATE YEAR TO MINUTE,
        EMPLEADO_DIRECCION VARCHAR (50),
        EMPLEADO_SITUACION INTEGER DEFAULT 1,
        PRIMARY KEY (EMPLEADO_ID)
    );

    CREATE TABLE PEDIDOS(
        PEDIDO_ID SERIAL NOT NULL,
        PEDIDO_CLIENTE INTEGER,
        PEDIDO_EMPLEADO INTEGER,
        PEDIDO_PLATILLO VARCHAR (20),
        PEDIDO_PLATO VARCHAR (20),
        PEDIDO_BEBIDA VARCHAR (20),
        PEDIDO_POSTRE VARCHAR (20),
        PEDIDO_OBSERVACIONES VARCHAR (50),
        PEDIDO_SITUACION INTEGER DEFAULT 1,
        PRIMARY KEY (PEDIDO_ID),
        FOREIGN KEY (PEDIDO_CLIENTE) REFERENCES CLIENTES (CLIENTE_ID),
        FOREIGN KEY (PEDIDO_EMPLEADO) REFERENCES EMPLEADOS (EMPLEADO_ID)
    );

    ALTER TABLE PEDIDOS ADD CLIENTE_completo VARCHAR(50);
    ALTER TABLE PEDIDOS ADD EMPLEADO_completo VARCHAR(50);