CREATE DATABASE CAFETERIA

    CREATE TABLE CLIENTES (
        CLIENTE_ID SERIAL NOT NULL,
        CLIENTE_NOMBRE VARCHAR (25),
        CLIENTE_APELLIDO VARCHAR (25),
        CLIENTE_GENERO VARCHAR(50),
        CLIENTE_CORREO VARCHAR(50),
        CLIENTE_TELEFONO INTEGER,
        CLIENTE_SITUACION INTEGER DEFAULT 1,
        PRIMARY KEY (CLIENTE_ID)
    );

    CREATE TABLE EMPLEADOS(
        EMPLEADO_ID SERIAL NOT NULL,
        EMPLEADO_NOMBRE VARCHAR (25),
        EMPLEADO_APELLIDO VARCHAR (25),
        EMPLEADO_GENERO VARCHAR (15),
        EMPLEADO_PUESTO VARCHAR (20),
        EMPLEADO_NACIMIENTO DATE YEAR TO MINUTE,
        EMPLEADO_TELEFONO INTEGER,
        EMPLEADO_CORREO VARCHAR (50),
        EMPLEADO_ESTADO VARCHAR (15),
        EMPLEADO_CONTRA DATE YEAR TO MINUTE,
        EMPLEADO_DIRECCION VARCHAR (50),
        EMPLEADO_SITUACION INTEGER DEFAULT 1,
        PRIMARY KEY (EMPLEADO_ID)
    );

    CREATE TABLE PEDIDOS(
        PED_ID SERIAL NOT NULL,
        PED_CLIENTE INTEGER,
        PED_EMPLEADO INTEGER,
        PED_PLATILLO VARCHAR (20),
        PED_PLATO VARCHAR (20),
        PED_BEBIDA VARCHAR (20),
        PED_POSTRE VARCHAR (20),
        PED_REFACCIONES VARCHAR (20),
        PRIMARY KEY (PED_ID),
        FOREIGN KEY (PED_CLIENTE) REFERENCES CLIENTES (CLIE_ID),
        FOREIGN KEY (PED_EMPLEADO) REFERENCES EMPLEADOS (EMP_ID)
    );