CREATE DATABASE CAFETERIA

    CREATE TABLE CLIENTES(
        CLIE_ID SERIAL NOT NULL,
        CLIE_NOMBRE VARCHAR (25),
        CLIE_APELLIDO VARCHAR (25),
        CLIE_EMAIL VARCHAR (50),
        CLIE_TELEFONO INTEGER,
        CLIE_SITUACION INTEGER DEFAULT 1,
        PRIMARY KEY (CLIE_ID)
    );

    CREATE TABLE EMPLEADOS(
        EMP_ID SERIAL NOT NULL,
        EMP_NOMBRE VARCHAR (25),
        EMP_APELLIDO VARCHAR (25),
        EMP_PUESTO VARCHAR (20),
        EMP_SITUACION INTEGER DEFAULT 1,
        PRIMARY KEY (EMP_APELLIDO)
    );

    CREATE TABLE PEDIDOS(
        PED_ID SERIAL NOT NULL,
        PED_CLIENTE INTEGER,
        PED_EMPLEADO INTEGER,
        PED_PLATILLO VARCHAR (20),
        PED_PLATO VARCHAR (20),
        PED_BEBIDA VARCHAR (20),
        PED_POSTRE VARCHAR (20),
        PED_REFACCIONES VARCHAR (20),
        PRIMARY KEY (PED_ID),
        FOREIGN KEY (PED_CLIENTE) REFERENCES CLIENTES (CLIE_ID),
        FOREIGN KEY (PED_EMPLEADO) REFERENCES EMPLEADOS (EMP_ID)
    );